### ISSUE TITLE
Issue: chr22_PATERNAL:25,206,302-25,206,446

### ISSUE THREAD

**Issue by jzook** [marbl/HG002-issues#417]
paternal haplotype seems to be missing 70bp of sequence for unclear reasons (identified by GIAB v4.2.1 benchmark)
<img width="1228" alt="Screenshot 2023-03-16 at 2 45 24 PM" src="https://user-images.githubusercontent.com/2439798/225722230-dc477e52-ab0f-42b9-b738-c7b58ee2493f.png">

**Comment by nhansen** [comment]
Although two small corrections were made in the transition from v0.7 to v0.9, the large insertion wasn't caught by any of our variant calling, so that error remains in v0.9. This issue will be transferred to v0.9 and dealt with there:
<img width="1372" alt="image" src="https://github.com/marbl/HG002-issues/assets/2365395/d40b86e1-8ca8-4b85-a655-e564711ae638">
